-- create the datatase
CREATE DATABASE flight_analytics;


-- create a role to the terraform user with minimal privileges
CREATE ROLE TERRAFORM_MANAGER;

-- allow the role to create schema
GRANT CREATE SCHEMA ON DATABASE FLIGHT_ANALYTICS TO ROLE TERRAFORM_MANAGER;

-- allow the role to access to the database
GRANT USAGE ON DATABASE FLIGHT_ANALYTICS TO ROLE TERRAFORM_MANAGER;

-- allow the role to access all schemas in the database
GRANT ALL ON ALL SCHEMAS IN DATABASE FLIGHT_ANALYTICS TO ROLE TERRAFORM_MANAGER;

-- allow the role to create a warehouse
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE TERRAFORM_MANAGER;

-- create terraform user
USE ROLE ACCOUNTADMIN;

CREATE USER TERRAFORM_SVC
    TYPE = SERVICE
    COMMENT = "Service user for Terraforming Snowflake"
    RSA_PUBLIC_KEY = "<RSA_PUBLIC_KEY_HERE>";
    
-- grant the role to the user
GRANT ROLE TERRAFORM_MANAGER TO USER TERRAFORM_SVC

 GRANT OWNERSHIP ON SCHEMA FLIGHT_ANALYTICS.SILVER TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;
 GRANT CREATE TABLE ON SCHEMA FLIGHT_ANALYTICS.SILVER TO ROLE ACCOUNTADMIN;
 GRANT CREATE STAGE ON SCHEMA FLIGHT_ANALYTICS.SILVER TO ROLE ACCOUNTADMIN;
 GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FLIGHT_ANALYTICS.SILVER TO ROLE ACCOUNTADMIN;
 GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN FLIGHT_ANALYTICS.SILVER TO ROLE ACCOUNTADMIN;
 GRANT USAGE ON SCHEMA FLIGHT_ANALYTICS.SILVER TO ROLE ACCOUNTADMIN;
 GRANT USAGE ON WAREHOUSE FLIGHT_WH TO ROLE ACCOUNTADMIN;
 GRANT OPERATE ON WAREHOUSE FLIGHT_WH TO ROLE ACCOUNTADMIN;
 GRANT OWNERSHIP ON WAREHOUSE FLIGHT_WH TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;

 GRANT CREATE TABLE ON SCHEMA FLIGHT_ANALYTICS.GOLD TO ROLE ACCOUNTADMIN;
 GRANT CREATE STAGE ON SCHEMA FLIGHT_ANALYTICS.GOLD TO ROLE ACCOUNTADMIN;
 GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FLIGHT_ANALYTICS.GOLD TO ROLE ACCOUNTADMIN;
 GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA FLIGHT_ANALYTICS.GOLD TO ROLE ACCOUNTADMIN;
 GRANT USAGE ON SCHEMA FLIGHT_ANALYTICS.GOLD TO ROLE ACCOUNTADMIN;
 GRANT OWNERSHIP ON SCHEMA FLIGHT_ANALYTICS.GOLD TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;

 GRANT CREATE TABLE ON SCHEMA FLIGHT_ANALYTICS.BRONZE TO ROLE ACCOUNTADMIN;
 GRANT CREATE STAGE ON SCHEMA FLIGHT_ANALYTICS.BRONZE TO ROLE ACCOUNTADMIN;
 GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FLIGHT_ANALYTICS.BRONZE TO ROLE ACCOUNTADMIN;
 GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA FLIGHT_ANALYTICS.BRONZE TO ROLE ACCOUNTADMIN;
 GRANT USAGE ON SCHEMA FLIGHT_ANALYTICS.BRONZE TO ROLE ACCOUNTADMIN;
 GRANT OWNERSHIP ON SCHEMA FLIGHT_ANALYTICS.BRONZE TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;
